services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped

    volumes:
      - ./authelia:/config

    environment:
      TZ: ${TZ}

    networks:
      - local-network
      - traefik

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:9091/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    security_opt:
      - no-new-privileges:true

  traefik:
    image: traefik:v3.6.13
    container_name: traefik
    restart: unless-stopped

    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik"
      - "--providers.file.filename=/etc/traefik/certificates.yml"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--log=true"
      - "--log.level=INFO"

    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

    networks:
      - traefik

    security_opt:
      - no-new-privileges:true

networks:
  traefik:
    driver: bridge
  local-network:
    external: true
