#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_EXPORTER_USER}') THEN
    CREATE ROLE ${POSTGRES_EXPORTER_USER} LOGIN PASSWORD '${POSTGRES_EXPORTER_PASS}';
  END IF;
END
\$\$;
GRANT pg_monitor TO ${POSTGRES_EXPORTER_USER};
EOSQL
