services:
    labelstudio:
        image: heartexlabs/label-studio:${LABEL_STUDIO_VERSION}
        container_name: label-studio
        restart: unless-stopped
        ports:
            - "${HOST_PORT}:8080"
        volumes:
            - labelstudio_data:/label-studio/data
            - labelstudio_projects:/label-studio/projects
        environment:
            - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
            - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
            - LABEL_STUDIO_HOST=0.0.0.0
        command: label-studio start --host 0.0.0.0 --port 8080

volumes:
    labelstudio_data:
    labelstudio_projects:
