services:
  janus-gateway:
    image: janus-custom:latest
    container_name: janus-gateway
    ports:
      - "8088:8088"
      - "8188:8188"
      - "10000-10200:10000-10200/udp"
    volumes:
      - ./conf:/usr/local/etc/janus
    restart: unless-stopped
