services:
  janus:
    image: ${JANUS_IMAGE}
    container_name: ${JANUS_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - JANUS_LOG_LEVEL=${JANUS_LOG_LEVEL}
    ports:
      - '${JANUS_HTTP_PORT}:8088'
      - '${JANUS_WS_PORT}:8188'
      # Hanya expose HTTPS/WSS jika kamu aktifkan di config & ingin dipakai
      # - '${JANUS_HTTPS_PORT}:8089'
      # - '${JANUS_WSS_PORT}:8189'
      - '${JANUS_MEDIA_PORT_START}-${JANUS_MEDIA_PORT_END}:${JANUS_MEDIA_PORT_START}-${JANUS_MEDIA_PORT_END}/udp'
    volumes:
      - ./conf:/usr/local/etc/janus
      - ./logs:/usr/local/var/log/janus
