services:
  janus-gateway:
    image: anggamys/janus-custom:latest
    container_name: janus-gateway
    restart: unless-stopped

    ports:
      - "8088:8088"
      - "8188:8188"
      - "10000-10020:10000-10020/udp"   # batasi range UDP biar tidak boros socket

    volumes:
      - ./conf:/usr/local/etc/janus:ro
      - ./logs:/var/log/janus

    environment:
      - JANUS_LOG_LEVEL=2
      - JANUS_DEBUG_AUDIO=0
      - JANUS_DEBUG_VIDEO=0

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 400M
        reservations:
          memory: 256M

    networks:
      - janus-net

networks:
  janus-net:
    driver: bridge

