services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich_server
    restart: unless-stopped
    ports:
      - "2283:2283"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    volumes:
      - ./data/library:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - local-network

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich_ml
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/model-cache:/cache
    networks:
      - local-network

  redis:
    image: valkey/valkey:9
    container_name: immich_redis
    restart: unless-stopped
    command: >
      redis-server
      --save 60 1
      --appendonly yes
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-network

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-network

networks:
  local-network:
    external: true
