services:
  jenkins:
    image: jenkins/jenkins:2.462.2-lts-jdk17
    container_name: jenkins_local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      TZ: "Asia/Jakarta"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=true"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - local-network

volumes:
  jenkins_home:

networks:
  local-network:
    external: true
