services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION:-1.18}
    container_name: vault
    restart: unless-stopped

    ports:
      - "${VAULT_BIND_ADDRESS:-127.0.0.1}:8200:8200"
      - "${VAULT_CLUSTER_BIND_ADDRESS:-127.0.0.1}:8201:8201"

    environment:
      VAULT_API_ADDR: "${VAULT_API_ADDR:-https://127.0.0.1:8200}"
      VAULT_CACERT: "/vault/userconfig/tls/ca.crt"

    cap_add:
      - IPC_LOCK

    volumes:
      - ./audit:/vault/audit
      - ./config:/vault/config
      - ./data:/vault/data
      - ./file:/vault/file
      - ./logs:/vault/logs
      - ./userconfig:/vault/userconfig
      - ./plugins:/vault/plugins

    command: vault server -config=/vault/config/vault-config.hcl
    security_opt:
      - no-new-privileges:true
