services:
  ovenmediaengine:
    image: airensoft/ovenmediaengine:latest
    container_name: ovenmediaengine
    environment:
      OME_HOST_IP: 192.168.1.10 # Ganti dengan IP host Anda
    volumes:
      - ./conf:/opt/ovenmediaengine/bin/origin_conf
      - ./logs:/var/log/ovenmediaengine
    ports:
      - "1935:1935" # RTMP
      - "9999:9999/udp" # SRT input
      - "9000:9000" # Web UI / Origin
      - "3333:3333" # LLHLS playback
      - "3478:3478" # WebRTC TCP relay
      - "10000-10009:10000-10009/udp" # WebRTC UDP ports
    # restart: unless-stopped
