services:
  redis:
    image: redis:7-alpine
    container_name: redis_service
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - local-network

volumes:
  redis_data:

networks:
  local-network:
    external: true
