version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0del@b08
      MYSQL_DATABASE: initialize_db
      MYSQL_USER: WorkSpace
      MYSQL_PASSWORD: C0del@b08
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: WorkSpace
      PMA_PASSWORD: C0del@b08
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
