services:
    mysql:
        image: mysql:8.0
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mysql-admin-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        container_name: phpmyadmin_container
        restart: always
        environment:
            PMA_HOST: mysql
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - mysql-admin-net

volumes:
    mysql_data:

networks:
    mysql-admin-net:
        driver: bridge
